name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        For security vulnerabilities, please see [SECURITY.md](../SECURITY.md) instead.

  - type: input
    id: version
    attributes:
      label: SDK Version
      placeholder: "e.g. 1.0.4 (pip show formatex)"
    validations:
      required: true

  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: "e.g. 3.12.0 (python --version)"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Minimal code snippet that reproduces the issue.
      render: python
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior / Error Output
      render: shell

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I am on the latest SDK version
          required: true
        - label: I searched existing issues before opening this one
          required: true
