name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the use case that's currently not supported.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed API / Solution
      description: How would you like this to work? Code sketches welcome.
      render: python

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds you've tried?

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues before opening this one
          required: true
